package com.connexiz.app.reveng;
// Generated Aug 12, 2016 9:43:28 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CourseTeacherId generated by hbm2java
 */
@Embeddable
public class CourseTeacherId implements java.io.Serializable {

	private Integer courseId;
	private Integer teacherId;
	private String rating;

	public CourseTeacherId() {
	}

	public CourseTeacherId(Integer courseId, Integer teacherId, String rating) {
		this.courseId = courseId;
		this.teacherId = teacherId;
		this.rating = rating;
	}

	@Column(name = "courseID")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "teacherID")
	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "rating", length = 20)
	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseTeacherId))
			return false;
		CourseTeacherId castOther = (CourseTeacherId) other;

		return ((this.getCourseId() == castOther.getCourseId()) || (this.getCourseId() != null
				&& castOther.getCourseId() != null && this.getCourseId().equals(castOther.getCourseId())))
				&& ((this.getTeacherId() == castOther.getTeacherId()) || (this.getTeacherId() != null
						&& castOther.getTeacherId() != null && this.getTeacherId().equals(castOther.getTeacherId())))
				&& ((this.getRating() == castOther.getRating()) || (this.getRating() != null
						&& castOther.getRating() != null && this.getRating().equals(castOther.getRating())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37 * result + (getTeacherId() == null ? 0 : this.getTeacherId().hashCode());
		result = 37 * result + (getRating() == null ? 0 : this.getRating().hashCode());
		return result;
	}

}
