package com.connexiz.app.reveng;
// Generated Aug 12, 2016 9:43:28 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CourseStudentId generated by hbm2java
 */
@Embeddable
public class CourseStudentId implements java.io.Serializable {

	private int courseId;
	private int studentId;
	private String grade;

	public CourseStudentId() {
	}

	public CourseStudentId(int courseId, int studentId) {
		this.courseId = courseId;
		this.studentId = studentId;
	}

	public CourseStudentId(int courseId, int studentId, String grade) {
		this.courseId = courseId;
		this.studentId = studentId;
		this.grade = grade;
	}

	@Column(name = "courseID", nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	@Column(name = "studentID", nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	@Column(name = "grade", length = 20)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseStudentId))
			return false;
		CourseStudentId castOther = (CourseStudentId) other;

		return (this.getCourseId() == castOther.getCourseId()) && (this.getStudentId() == castOther.getStudentId())
				&& ((this.getGrade() == castOther.getGrade()) || (this.getGrade() != null
						&& castOther.getGrade() != null && this.getGrade().equals(castOther.getGrade())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseId();
		result = 37 * result + this.getStudentId();
		result = 37 * result + (getGrade() == null ? 0 : this.getGrade().hashCode());
		return result;
	}

}
