package com.connexiz.app.reveng;
// Generated Aug 12, 2016 9:43:28 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentTeacherId generated by hbm2java
 */
@Embeddable
public class StudentTeacherId implements java.io.Serializable {

	private int studentId;
	private int teacherId;

	public StudentTeacherId() {
	}

	public StudentTeacherId(int studentId, int teacherId) {
		this.studentId = studentId;
		this.teacherId = teacherId;
	}

	@Column(name = "studentID", nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	@Column(name = "teacherID", nullable = false)
	public int getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentTeacherId))
			return false;
		StudentTeacherId castOther = (StudentTeacherId) other;

		return (this.getStudentId() == castOther.getStudentId()) && (this.getTeacherId() == castOther.getTeacherId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudentId();
		result = 37 * result + this.getTeacherId();
		return result;
	}

}
